spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3309/sell2?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non-null 
server:
  context-path: /sell
logging:
   pattern:
    console: "%d -%msg%n"
   #path: E://
   file: E://sell.log
   # level:
      #指定到某个类下的日志，才输出（类名）
  # level: error

